### ISSUE TITLE
Your Google Analytics implementation isn't tracking returning users

### ISSUE THREAD

**Issue by philipwalton** [jergason/blorg#3]
Just FYI, I happened to notice this and thought you might want to change it. You have this line in your Google Analytics initialization code:

```
ga('create', 'UA-20920851-2', 'jamisondance.com');
```

Which is going to try to set the `_ga` cookie on the cookie domain `jamisondance.com`, which will fail on `jamison.dance` (sweet domain name by the way!). You should update it to this:

```
ga('create', 'UA-20920851-2', 'auto');
```

The `'auto'` value uses [automatic cookie domain configuration](https://devsite.googleplex.com/analytics/devguides/collection/analyticsjs/cookies-user-id#automatic_cookie_domain_configuration), so if you change domains in the future it'll keep working.

The way it is now, tracking will still happen, but since the client ID isn't being stored in the cookie, a new ID will be generated on every pageload, which will make it look like every visit is from a unique person.

**Comment by jergason** [comment]
Open source is magical! Thanks for pointing this out!
